### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by trrahul** [WildGums/LogViewer#118]
Leave Your Message Below (don't delete this line though)
Hi, I have a WPF application that uses Autofac and I was wondering if it is possible to replace usage of Catel with Autofac and use this log viewer with my application? Thank you.

**Comment by GeertvanHorrik** [comment]
@trrahul at this stage we don't have any plans to support other containers. It is possible to forward types to the ServiceLocator (sort of a proxy), but services will either need to live in the ServiceLocator or you will have to implement your own IViewModelFactory that uses the Autofac container to resolve types.
