### ISSUE TITLE
Thank You. Nice project

### ISSUE THREAD

**Issue by LiorBanai** [WildGums/LogViewer#128]
Leave Your Message Below (don't delete this line though)

Hi,
I was going over this project and this gave me idea to add parser to my own open source project for parsing logs. I have created new repository specific for Catel logs [Analogy Catel Parser](https://github.com/Analogy-LogViewer/Analogy.LogViewer.CatelProject).

using your example logs I was able to create initial parser:
![Example](https://user-images.githubusercontent.com/36262995/74048361-ba913c80-49da-11ea-9660-2f59daf35e22.jpg)
![Example2](https://user-images.githubusercontent.com/36262995/74048374-c0871d80-49da-11ea-9b5d-917a048464da.jpg)

so thanks you :)

**Comment by GeertvanHorrik** [comment]
Thanks, project looks great, we will check it out! Maybe we can obsolete LogViewer in favor of this tool later ;-)
