### ISSUE TITLE
Fails to open log file when LogViewer reads the same logfile

### ISSUE THREAD

**Issue by byrialsen** [WildGums/LogViewer#3]
### Steps to reproduce

In my custom LogFileListener for UWP I open the logfile with a call like this:

```csharp
IRandomAccessStream stream = await LogStorageFile.OpenAsync(FileAccessMode.ReadWrite);
```

### Expected behaviour

The logfile should be opened without exceptions

### Actual behaviour

The logfile sometimes return an Access Denied Exception

### Solution proposal

In file: [LogFileService](https://github.com/WildGums/LogViewer/blob/develop/src/LogViewer/Services/LogReaderService.cs)

replace this line:

```csharp
stream = new FileStream(fileNode.FileInfo.FullName, FileMode.Open, FileAccess.Read);
```

with this one:

```csharp
stream = new FileStream(fileNode.FileInfo.FullName, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete);
```

**Comment by byrialsen** [comment]
@GeertvanHorrik . Don't you think this should be fixed in the future?

**Comment by GeertvanHorrik** [comment]
Sure, we just didn't have time for it yet.

**Comment by GeertvanHorrik** [comment]
You can always PR if you wish, that saves us a bit of work :)
